### ISSUE TITLE
Error: Cannot find module './package.json'

### ISSUE THREAD

**Issue by lunafi-evan** [nuxt-community/google-adsense-module#3]
To recreate this I did:

* `vue init nuxt-community/starter-template vue-adsense-test`
* `cd vue-adsense-test`
* `npm i`
* `npm i -S @nuxtjs/google-adsense`
* added adsense module to nuxt.config.js
---
After installing 1.0.1 and adding this to my `nuxt.config.js`

```
    ['@nuxtjs/google-adsense', { id: '<my id>' }],    
```

This is logged to the terminal while nuxt is starting up

```

> vue-adsense-test@1.0.0 dev /home/evan/devel/temp/vue-adsense-test
> nuxt

{ Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/evan/devel/temp/vue-adsense-test/node_modules/@nuxtjs/google-adsense/lib/module.js:61:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at ModuleContainer._callee2$ (/home/evan/devel/temp/vue-adsense-test/node_modules/nuxt/lib/core/module.js:108:16)
    at tryCatch (/home/evan/devel/temp/vue-adsense-test/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/evan/devel/temp/vue-adsense-test/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/home/evan/devel/temp/vue-adsense-test/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21) code: 'MODULE_NOT_FOUND' }
  nuxt:build App root: /home/evan/devel/temp/vue-adsense-test +0ms
```

I get this in the browser: `Cannot GET /` and this in the browser console (Chrome):
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by lunafi-evan** [comment]
looks like `lib/module` is trying to import package.json when it doesn't exist in that path

**Comment by lunafi-evan** [comment]
https://github.com/nuxt-community/google-adsense-module/blob/master/lib/module.js#L61

**Comment by tmorehouse** [comment]
If you manually edit the module.js file to be `../package.json` it _should_ work.

**Comment by lunafi-evan** [comment]
@tmorehouse yup, just made a PR https://github.com/nuxt-community/google-adsense-module/pull/4

**Comment by tmorehouse** [comment]
Hehe, I just made one as well.

**Comment by lunafi-evan** [comment]
beat you by about 20 seconds :)

**Comment by tmorehouse** [comment]
I'll close mine

**Comment by tmorehouse** [comment]
I re-based your PR to the new `dev` branch.

There is on other fix I would like to add before re-publishing on NPM (ads shouldn't refresh when the route hash changes, unless the router is in `hash` mode)

**Comment by lunafi-evan** [comment]
sounds good, thanks! this module will be a really awesome addition to the community

**Comment by tmorehouse** [comment]
A new version has been published to NPM with your the fix, and some additional new options

**Comment by tmorehouse** [comment]
@lunafi-evan could you try out the new release and see if you see any issues?

**Comment by lunafi-evan** [comment]
@tmorehouse everything's looking good in 1.1.1!
